services:
  web:
    image: odin-prod
    build:
      context: .
      target: production
    restart: always
    environment:
      - WORKERS=1
      - LOG_LEVEL=INFO
      - ANTHROPIC_API_KEY
      - SEARXNG_SECRET

  searxng:
    restart: always

  searxng-valkey:
    restart: always

  odin-valkey:
    restart: always
