from collections.abc import AsyncIterator

class Valkey:
    @classmethod
    def from_url(cls, url: str) -> Valkey: ...
    async def aclose(self) -> None: ...
    async def flushdb(self) -> bool: ...
    async def get(self, name: str) -> bytes | None: ...
    async def incr(self, name: str) -> int: ...
    async def expireat(self, name: str, when: int) -> bool: ...
    async def expire(self, name: str, time: int) -> bool: ...
    async def lpush(self, name: str, *values: str | bytes) -> int: ...
    async def ltrim(self, name: str, start: int, end: int) -> bool: ...
    async def lrange(self, name: str, start: int, end: int) -> list[bytes]: ...
    async def set(
        self,
        name: str,
        value: str | bytes,
        *,
        nx: bool = ...,
        ex: int | None = ...,
        exat: int | None = ...,
    ) -> bool | None: ...
    async def delete(self, *names: str) -> int: ...
    def scan_iter(
        self, match: str | None = ..., count: int | None = ...
    ) -> AsyncIterator[bytes]: ...
